[external]
host = "https://github.com/JepEtau/external_rehost/releases/download/external"
do_cache = false
ffmpeg_name = "FFmpeg"
vspython_name = "VS python"
avs_name = "AviSynth+ plugins"

[external.win32]
do_cache = false

# Windows
[external.win32.ffmpeg]
filename = "ffmpeg-release-essentials.zip"

[external.win32.vspython]
filename = "vspython.zip"

# Linux
[external.linux.ffmpeg]
filename = "ffmpeg-2025-11-12-git-6cdd2cbe32-essentials_build_linux.zip"
skip=false


