import argparse
import fileinput
import os.path
import sys
import signal


def main():
    parser = argparse.ArgumentParser(description="Patch the python script generated by pyside6-uic")
    parser.add_argument("--file", help="file to patch")
    arguments = parser.parse_args()

    if not os.path.isfile(arguments.file):
        print(f"Error: file does not exist")

    for line in fileinput.input(arguments.file, inplace=True):
        search_expression = "../../icons/"
        replace_expression = "./ui/icons/"
        if search_expression in line:
            line = line.replace(search_expression, replace_expression)
        sys.stdout.write(line)



if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    main()

